
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.99"
  
loans:
  message: "Loans related Prod APIs"
  contactDetails:
    name: "User Support - Prod Owner"
    email: "prodowner@jayslabs.com"
  onCallSupport:
  - (800) 1234567
  - (800) 1234568